# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugs_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pk',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='postsection',
            options={'ordering': ('pk',), 'verbose_name': 'post section', 'verbose_name_plural': 'post sections'},
        ),
    ]
